site_name: KIE (Knowledge Is Everything)
theme:
  name: material
repo_url: https://github.com/alexanderjophus/kie

nav:
    - Home: 'index.md'
    - State of Things: 'state-of-things.md'
    - Pipeline Outline: 'pipeline-outline.md'
    - User Guide: 'user-guide.md'
    - How To: 
      - Use: 'howto/use.md'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
