apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: ingestion
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PACHD_SERVICE_HOST
          value: pachd.pachd.svc.cluster.local
        - name: PACHD_SERVICE_PORT
          value: "30650"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion
spec:
  selector:
    app: ingestion
  ports:
  - port: 8080
    targetPort: 8080